# Dockerfile.mysql
FROM mysql:8.0

# Init DB and user
ENV MYSQL_DATABASE=app_db \
    MYSQL_USER=app_user \
    MYSQL_PASSWORD=1234 \
    MYSQL_ROOT_PASSWORD=root_password

# Default MySQL port
EXPOSE 3306
